# live_config_reload = true

[window]
startup_mode = "Maximized"
padding = { x = 2, y = 2}

[scrolling]
history = 10000
multiplier = 10

[font]
normal = {family = "CaskaydiaCove NF", style = "Regular"}
bold = {family = "CaskaydiaCove NF", style = "Bold"}
italic = {family = "CaskaydiaCove NF", style = "Italic"}
bold_italic = {family = "CaskaydiaCove NF", style = "Bold Italic"}
size = 13
offset = { x = 0, y = 0}
glyph_offset = { x = 0, y = 0}

[colors]
draw_bold_text_with_bright_colors = true
[colors.primary]
background = "#24273a"
foreground = "#cad3f5"
dim_foreground = "#8087a2"
bright_foreground = "#cad3f5"

[colors.cursor]
text = "#24273a"
cursor = "#f4dbd6"

[colors.vi_mode_cursor]
text = "#24273a"
cursor = "#b7bdf8"

[colors.search.matches]
foreground = "#24273a"
background = "#a5adcb"

[colors.search.focused_match]
foreground = "#24273a"
background = "#a6da95"

[colors.footer_bar]
foreground = "#24273a"
background = "#a5adcb"

[colors.hints.start]
foreground = "#24273a"
background = "#eed49f"

[colors.hints.end]
foreground = "#24273a"
background = "#a5adcb"

[colors.selection]
text = "#24273a"
background = "#f4dbd6"

[colors.normal]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[colors.bright]
black = "#5b6078"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#a5adcb"

[colors.dim]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[[colors.indexed_colors]]
index = 16
color = "#f5a97f"

[[colors.indexed_colors]]
index = 17
color = "#f4dbd6"
[cursor]
unfocused_hollow = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{key = "C", mods = "Command|Shift", action = "Copy"},
{key = "V", mods = "Command|Shift", action = "Paste"}
]
